apiVersion: v1
kind: Namespace
metadata:
  name: gw-405
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: gw-405
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: cloudadc/cafe:1.4
        name: backend
        ports:
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: gw-405
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: app
  type: ClusterIP
