apiVersion: k8s.nginx.org/v1alpha1
kind: GlobalConfiguration 
metadata:
  name: nginx-configuration
  namespace: nginx-ingress
spec:
  listeners:
  - name: dns-udp
    port: 5353
    protocol: UDP
  - name: dns-tcp
    port: 5353
    protocol: TCP
  - name: ttcp-tcp
    port: 5001
    protocol: TCP
  - name: https-tcp
    port: 8443
    protocol: TCP
  - name: ttcp-udp
    port: 5001
    protocol: UDP
