apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-3-3-1
  namespace: f5-manage02
spec:
  host: gw.f5manage02.test.cmbc.com
  ingressClassName: nginx-gw
  upstreams:
  - name: coffee-app
    service: coffee-svc
    port: 80
    sessionCookie:
      enable: true
      name: srv_id
      path: /coffee
      expires: 1h
      domain: .test.cmbc.com
      httpOnly: false
      secure: true
  routes:
  - path: /coffee
    action:
      pass: coffee-app
