apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea
  namespace: f5-manage03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tea
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
      - name: tea
        image: artifactory.dev.cmbc.cn:31345/net-docker-ver-local/nginx/cafe:1.5-aarch64
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  namespace: f5-manage03
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: tea
