apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-012
  namespace: gw-012
spec:
  host: gw012.example.com
  upstreams:
  - name: foo-v1
    service: foo-v1-svc
    port: 80
  - name: foo-v2
    service: foo-v2-svc
    port: 80
  routes:
  - path: /
    location-snippets: "mirror /mirror;"
    action:
      pass: foo-v1
  - path: /mirror
    location-snippets: "internal;"
    action:
      pass: foo-v2


