= VPC
:toc: manual

== default network

=== network

[source, bash]
----
gcloud compute networks list
----

link:default.json[default.json]

[source, json]
----
{
    "autoCreateSubnetworks": true,
    "kind": "compute#network",
    "name": "default",
    "networkFirewallPolicyEnforcementOrder": "AFTER_CLASSIC_FIREWALL",
    "x_gcloud_bgp_routing_mode": "REGIONAL",
    "x_gcloud_subnet_mode": "AUTO"
}
----

=== subnets

[source, bash]
----
gcloud compute networks subnets list
----

link:default-subnets.json[default-subnets.json]

|===
|gatewayAddress |ipCidrRange |name |privateIpGoogleAccess |purpose |stackType |network |region

| 10.128.0.1
| 10.128.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| us-central1

| 10.132.0.1
| 10.132.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| europe-west1

| 10.138.0.1
| 10.138.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| us-west1

| 10.140.0.1
| 10.140.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| asia-east1

| 10.142.0.1
| 10.142.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| us-east1

| 10.146.0.1
| 10.146.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| asia-northeast1

| 10.148.0.1
| 10.148.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| asia-southeast1

| 10.150.0.1
| 10.150.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| us-east4

| 10.152.0.1
| 10.152.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| australia-southeast1

| 10.154.0.1
| 10.154.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| europe-west2

| 10.156.0.1
| 10.156.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| europe-west3

| 10.160.0.1
| 10.160.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| asia-south1

| 10.164.0.1
| 10.164.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| europe-west4

| 10.166.0.1
| 10.166.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| europe-north1

| 10.168.0.1
| 10.168.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| us-west2

| 10.180.0.1
| 10.180.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| us-west3

| 10.182.0.1
| 10.182.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| us-west4

| 10.186.0.1
| 10.186.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| europe-central2

| 10.194.0.1
| 10.194.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| southamerica-west1

| 10.196.0.1
| 10.196.0.0/20
| default
| false
| PRIVATE
| IPV4_ONLY
| default
| us-east7

|10.202.0.1
|10.202.0.0/20
|default
|false
|PRIVATE
|IPV4_ONLY
|default
|us-east5

|10.206.0.1
|10.206.0.0/20
|default
|false
|PRIVATE
|IPV4_ONLY
|default
|us-south1

|10.208.0.1
|10.208.0.0/20
|default
|false
|PRIVATE
|IPV4_ONLY
|default
|me-west1
|===

=== routes

[source, bash]
----
gcloud compute routes list
----

link:default-routes.json[default-routes.json]

|===
|destRange |name |priority |network |nextHopNetwork

|0.0.0.0/0
|default-route-a9424e017df6cc72
|1000
|default
|

|10.154.0.0/20
|default-route-120b0e8e1a1e6600
|0
|default
|default

|10.160.0.0/20
|default-route-185361fb8189dc54
|0
|default
|default

|10.132.0.0/20
|default-route-1920fc2005167826
|0
|default
|default

|10.194.0.0/20
|default-route-263f56c558e23588
|0
|default
|default

|10.202.0.0/20
|default-route-2ac9262d4c41487b
|0
|default
|default

|10.140.0.0/20
|default-route-3589d5e6cf6657b9
|0
|default
|default

|10.138.0.0/20
|default-route-3999302cbd084b50
|0
|default
|default

|10.164.0.0/20
|default-route-468313b5bf1066c2
|0
|default
|default

|10.150.0.0/20
|default-route-561bda1e08a32613
|0
|default
|default

|10.128.0.0/20
|default-route-632dca7cafdb3528
|0
|default
|default

|10.186.0.0/20
|default-route-7897f5199529c84b
|0
|default
|default

|10.182.0.0/20
|default-route-817fc4d84c6484bc
|0
|default
|default

|10.146.0.0/20
|default-route-85e8c45f9ba3ad71
|0
|default
|default

|10.180.0.0/20
|default-route-8a1b6b72c04e1c19
|0
|default
|default

|10.142.0.0/20
|default-route-b9ecc55c1f8a18e0
|0
|default
|default

|10.148.0.0/20
|default-route-c0920f75992bc86b
|0
|default
|default

|10.152.0.0/20
|default-route-c316d6acc7332b4b
|0
|default
|default

|10.166.0.0/20
|default-route-d431f58d6523f27a
|0
|default
|default

|10.206.0.0/20
|default-route-d62ba1b5651c11e7
|0
|default
|default


|10.208.0.0/20
|default-route-d66d5f3c08efee80
|0
|default
|default


|10.168.0.0/20
|default-route-e7174b8619696a58
|0
|default
|default

|10.156.0.0/20
|default-route-eccb105ce62524b8
|0
|default
|default

|10.196.0.0/20
|default-route-eebfbfdb149fa172
|0
|default
|default
|===

=== firewall rules

[source, bash] 
----
gcloud compute firewall-rules list
----

link:default-firewall-rules.json[default-firewall-rules.json]

|===
|name |direction |network |priority |sourceRanges |allowedProtocolPort |logConfigEnable
|default-allow-icmp
|INGRESS
|default
|65534
|0.0.0.0/0
|icmp
|false

|default-allow-internal
|INGRESS
|default
|65534
|10.128.0.0/9
|tcp/(0-65535)
|false

|default-allow-rdp
|INGRESS
|default
|65534
|0.0.0.0/0
|tcp/3389
|false

|default-allow-ssh
|INGRESS
|default
|65534
|0.0.0.0/0
|tcp/22
|false
|===


== auto mode network

[source. bash]
.*gcloud compute networks list*
----
NAME: mynetwork
SUBNET_MODE: AUTO
BGP_ROUTING_MODE: REGIONAL
IPV4_RANGE: 
GATEWAY_IPV4: 
----

[source, bash]
.*gcloud compute networks subnets list*
----
NAME: mynetwork
REGION: us-central1
NETWORK: mynetwork
RANGE: 10.128.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-west1
NETWORK: mynetwork
RANGE: 10.132.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-west1
NETWORK: mynetwork
RANGE: 10.138.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: asia-east1
NETWORK: mynetwork
RANGE: 10.140.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-east1
NETWORK: mynetwork
RANGE: 10.142.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: asia-northeast1
NETWORK: mynetwork
RANGE: 10.146.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: asia-southeast1
NETWORK: mynetwork
RANGE: 10.148.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-east4
NETWORK: mynetwork
RANGE: 10.150.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: australia-southeast1
NETWORK: mynetwork
RANGE: 10.152.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-west2
NETWORK: mynetwork
RANGE: 10.154.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-west3
NETWORK: mynetwork
RANGE: 10.156.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: asia-south1
NETWORK: mynetwork
RANGE: 10.160.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-west4
NETWORK: mynetwork
RANGE: 10.164.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-north1
NETWORK: mynetwork
RANGE: 10.166.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-west2
NETWORK: mynetwork
RANGE: 10.168.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-west3
NETWORK: mynetwork
RANGE: 10.180.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-west4
NETWORK: mynetwork
RANGE: 10.182.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-central2
NETWORK: mynetwork
RANGE: 10.186.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: southamerica-west1
NETWORK: mynetwork
RANGE: 10.194.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-east5
NETWORK: mynetwork
RANGE: 10.202.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-south1
NETWORK: mynetwork
RANGE: 10.206.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 
----

[source, bash]
.*gcloud compute routes list*
----
NAME: default-route-10c1f731bb6d705e
NETWORK: mynetwork
DEST_RANGE: 10.194.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-13f48ebbe0b6abbf
NETWORK: mynetwork
DEST_RANGE: 10.146.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-16d5efdacafedb30
NETWORK: mynetwork
DEST_RANGE: 10.206.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-1855dffbaaa4df22
NETWORK: mynetwork
DEST_RANGE: 10.180.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-2440d68673968337
NETWORK: mynetwork
DEST_RANGE: 10.128.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-2e85b5195efcb011
NETWORK: mynetwork
DEST_RANGE: 10.182.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-3bb36e360358c16a
NETWORK: mynetwork
DEST_RANGE: 10.132.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-3c2fdaf8708f5f18
NETWORK: mynetwork
DEST_RANGE: 10.150.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-4f997153cf1f1753
NETWORK: mynetwork
DEST_RANGE: 10.154.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-5a1afad8303687a1
NETWORK: mynetwork
DEST_RANGE: 10.186.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-5ae23ee135df3b1d
NETWORK: mynetwork
DEST_RANGE: 10.202.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-5ccfceb1be9100c0
NETWORK: mynetwork
DEST_RANGE: 10.148.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-98db287c782e8641
NETWORK: mynetwork
DEST_RANGE: 0.0.0.0/0
NEXT_HOP: default-internet-gateway
PRIORITY: 1000

NAME: default-route-a7269e7697dcca84
NETWORK: mynetwork
DEST_RANGE: 10.166.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-abe7d732ecee4b45
NETWORK: mynetwork
DEST_RANGE: 10.160.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-bc0ed7f55db50baf
NETWORK: mynetwork
DEST_RANGE: 10.140.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-bc929450bdd73daf
NETWORK: mynetwork
DEST_RANGE: 10.138.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-ccdd088c0670262b
NETWORK: mynetwork
DEST_RANGE: 10.164.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-eba7ffe7daeb934a
NETWORK: mynetwork
DEST_RANGE: 10.152.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-ee65722ea7e40ef3
NETWORK: mynetwork
DEST_RANGE: 10.156.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-f4ee05ac8700d4c3
NETWORK: mynetwork
DEST_RANGE: 10.168.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-f93e5c4095524370
NETWORK: mynetwork
DEST_RANGE: 10.142.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0
----

[source, bash]
.*gcloud compute firewall-rules list*
----
NAME: mynetwork-allow-custom
NETWORK: mynetwork
DIRECTION: INGRESS
PRIORITY: 65534
ALLOW: all
DENY: 
DISABLED: False

NAME: mynetwork-allow-icmp
NETWORK: mynetwork
DIRECTION: INGRESS
PRIORITY: 65534
ALLOW: icmp
DENY: 
DISABLED: False

NAME: mynetwork-allow-rdp
NETWORK: mynetwork
DIRECTION: INGRESS
PRIORITY: 65534
ALLOW: tcp:3389
DENY: 
DISABLED: False

NAME: mynetwork-allow-ssh
NETWORK: mynetwork
DIRECTION: INGRESS
PRIORITY: 65534
ALLOW: tcp:22
DENY: 
DISABLED: False
----

=== Delete VPC network Firewall rules

[source, bash]
----
for i in $(gcloud compute firewall-rules list | grep NAME | awk '{print $2}') ; do gcloud compute firewall-rules delete $i ; done
----

=== Delete VPC network

[source, bash]
----
gcloud compute networks delete default
----

=== Create VPC network

----
gcloud compute networks create mynetwork --project=qwiklabs-gcp-00-8f96e32795ef --subnet-mode=custom --mtu=1460 --bgp-routing-mode=regional 

gcloud compute networks subnets create vlan-1 --project=qwiklabs-gcp-00-8f96e32795ef --range=10.140.0.0/20 --stack-type=IPV4_ONLY --network=mynetwork --region=asia-east1 --enable-private-ip-google-access
gcloud compute networks subnets create vlan-2 --project=qwiklabs-gcp-00-8f96e32795ef --range=10.146.0.0/20 --stack-type=IPV4_ONLY --network=mynetwork --region=asia-northeast1 --enable-private-ip-google-access

gcloud compute firewall-rules create mynetwork-allow-custom --project=qwiklabs-gcp-00-8f96e32795ef --network=projects/qwiklabs-gcp-00-8f96e32795ef/global/networks/mynetwork --description=Allows\ connection\ from\ any\ source\ to\ any\ instance\ on\ the\ network\ using\ custom\ protocols. --direction=INGRESS --priority=65534 --source-ranges=10.140.0.0/20,10.146.0.0/20 --action=ALLOW --rules=all 
gcloud compute firewall-rules create mynetwork-allow-icmp --project=qwiklabs-gcp-00-8f96e32795ef --network=projects/qwiklabs-gcp-00-8f96e32795ef/global/networks/mynetwork --description=Allows\ ICMP\ connections\ from\ any\ source\ to\ any\ instance\ on\ the\ network. --direction=INGRESS --priority=65534 --source-ranges=0.0.0.0/0 --action=ALLOW --rules=icmp
gcloud compute firewall-rules create mynetwork-allow-rdp --project=qwiklabs-gcp-00-8f96e32795ef --network=projects/qwiklabs-gcp-00-8f96e32795ef/global/networks/mynetwork --description=Allows\ RDP\ connections\ from\ any\ source\ to\ any\ instance\ on\ the\ network\ using\ port\ 3389. --direction=INGRESS --priority=65534 --source-ranges=0.0.0.0/0 --action=ALLOW --rules=tcp:3389 
gcloud compute firewall-rules create mynetwork-allow-ssh --project=qwiklabs-gcp-00-8f96e32795ef --network=projects/qwiklabs-gcp-00-8f96e32795ef/global/networks/mynetwork --description=Allows\ TCP\ connections\ from\ any\ source\ to\ any\ instance\ on\ the\ network\ using\ port\ 22. --direction=INGRESS --priority=65534 --source-ranges=0.0.0.0/0 --action=ALLOW --rules=tcp:22
----

=== Create VM instance


----
gcloud compute instances create instance-1 --project=qwiklabs-gcp-00-8f96e32795ef --zone=asia-east1-a --machine-type=e2-micro --network-interface=network-tier=PREMIUM,subnet=vlan-1 --metadata=enable-oslogin=true --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=821998381447-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --create-disk=auto-delete=yes,boot=yes,device-name=instance-1,image=projects/debian-cloud/global/images/debian-11-bullseye-v20221206,mode=rw,size=10,type=projects/qwiklabs-gcp-00-8f96e32795ef/zones/us-east5-c/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any

gcloud compute instances create instance-2 --project=qwiklabs-gcp-00-8f96e32795ef --zone=asia-northeast1-c --machine-type=e2-micro --network-interface=network-tier=PREMIUM,subnet=vlan-2 --metadata=enable-oslogin=true --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=821998381447-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --create-disk=auto-delete=yes,boot=yes,device-name=instance-2,image=projects/debian-cloud/global/images/debian-11-bullseye-v20221206,mode=rw,size=10,type=projects/qwiklabs-gcp-00-8f96e32795ef/zones/us-east5-c/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
----

== custom mode networks

[source, bash]
.*gcloud compute networks list*
----
NAME: managementnet
SUBNET_MODE: CUSTOM
BGP_ROUTING_MODE: REGIONAL
IPV4_RANGE: 
GATEWAY_IPV4: 

NAME: mynetwork
SUBNET_MODE: CUSTOM
BGP_ROUTING_MODE: REGIONAL
IPV4_RANGE: 
GATEWAY_IPV4: 

NAME: privatenet
SUBNET_MODE: CUSTOM
BGP_ROUTING_MODE: REGIONAL
IPV4_RANGE: 
GATEWAY_IPV4: 
----

[source, bash]
.*gcloud compute networks subnets list*
----
NAME: managementsubnet-us
REGION: us-central1
NETWORK: managementnet
RANGE: 10.130.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-central1
NETWORK: mynetwork
RANGE: 10.128.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: privatesubnet-us
REGION: us-central1
NETWORK: privatenet
RANGE: 172.16.0.0/24
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-west1
NETWORK: mynetwork
RANGE: 10.132.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: privatesubnet-eu
REGION: europe-west1
NETWORK: privatenet
RANGE: 172.20.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-west1
NETWORK: mynetwork
RANGE: 10.138.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: asia-east1
NETWORK: mynetwork
RANGE: 10.140.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-east1
NETWORK: mynetwork
RANGE: 10.142.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: asia-northeast1
NETWORK: mynetwork
RANGE: 10.146.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: asia-southeast1
NETWORK: mynetwork
RANGE: 10.148.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-east4
NETWORK: mynetwork
RANGE: 10.150.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: australia-southeast1
NETWORK: mynetwork
RANGE: 10.152.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-west2
NETWORK: mynetwork
RANGE: 10.154.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-west3
NETWORK: mynetwork
RANGE: 10.156.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: asia-south1
NETWORK: mynetwork
RANGE: 10.160.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-west4
NETWORK: mynetwork
RANGE: 10.164.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-north1
NETWORK: mynetwork
RANGE: 10.166.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-west2
NETWORK: mynetwork
RANGE: 10.168.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-west3
NETWORK: mynetwork
RANGE: 10.180.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-west4
NETWORK: mynetwork
RANGE: 10.182.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-central2
NETWORK: mynetwork
RANGE: 10.186.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: southamerica-west1
NETWORK: mynetwork
RANGE: 10.194.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-east7
NETWORK: mynetwork
RANGE: 10.196.0.0/20
STACK_TYPE: 
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-east5
NETWORK: mynetwork
RANGE: 10.202.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-south1
NETWORK: mynetwork
RANGE: 10.206.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 
----

[source, bash]
.*gcloud compute routes list*
----
NAME: default-route-10c1f731bb6d705e
NETWORK: mynetwork
DEST_RANGE: 10.194.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-13f48ebbe0b6abbf
NETWORK: mynetwork
DEST_RANGE: 10.146.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-16d5efdacafedb30
NETWORK: mynetwork
DEST_RANGE: 10.206.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-1855dffbaaa4df22
NETWORK: mynetwork
DEST_RANGE: 10.180.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-2440d68673968337
NETWORK: mynetwork
DEST_RANGE: 10.128.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-2e85b5195efcb011
NETWORK: mynetwork
DEST_RANGE: 10.182.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-3bb36e360358c16a
NETWORK: mynetwork
DEST_RANGE: 10.132.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-3c2fdaf8708f5f18
NETWORK: mynetwork
DEST_RANGE: 10.150.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-4f997153cf1f1753
NETWORK: mynetwork
DEST_RANGE: 10.154.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-5a1afad8303687a1
NETWORK: mynetwork
DEST_RANGE: 10.186.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-5ae23ee135df3b1d
NETWORK: mynetwork
DEST_RANGE: 10.202.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-5ccfceb1be9100c0
NETWORK: mynetwork
DEST_RANGE: 10.148.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-64416061722937be
NETWORK: managementnet
DEST_RANGE: 10.130.0.0/20
NEXT_HOP: managementnet
PRIORITY: 0

NAME: default-route-98db287c782e8641
NETWORK: mynetwork
DEST_RANGE: 0.0.0.0/0
NEXT_HOP: default-internet-gateway
PRIORITY: 1000

NAME: default-route-9fd7f14f9fbac5d8
NETWORK: mynetwork
DEST_RANGE: 10.196.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-a7269e7697dcca84
NETWORK: mynetwork
DEST_RANGE: 10.166.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-abe7d732ecee4b45
NETWORK: mynetwork
DEST_RANGE: 10.160.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-b363cd475c103392
NETWORK: privatenet
DEST_RANGE: 0.0.0.0/0
NEXT_HOP: default-internet-gateway
PRIORITY: 1000

NAME: default-route-bc0ed7f55db50baf
NETWORK: mynetwork
DEST_RANGE: 10.140.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-bc929450bdd73daf
NETWORK: mynetwork
DEST_RANGE: 10.138.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-c30ec08ad33fd9df
NETWORK: privatenet
DEST_RANGE: 172.20.0.0/20
NEXT_HOP: privatenet
PRIORITY: 0

NAME: default-route-c944b03e57e1449a
NETWORK: privatenet
DEST_RANGE: 172.16.0.0/24
NEXT_HOP: privatenet
PRIORITY: 0

NAME: default-route-ccdd088c0670262b
NETWORK: mynetwork
DEST_RANGE: 10.164.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-d88735bf0ef1e49e
NETWORK: managementnet
DEST_RANGE: 0.0.0.0/0
NEXT_HOP: default-internet-gateway
PRIORITY: 1000

NAME: default-route-eba7ffe7daeb934a
NETWORK: mynetwork
DEST_RANGE: 10.152.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-ee65722ea7e40ef3
NETWORK: mynetwork
DEST_RANGE: 10.156.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-f4ee05ac8700d4c3
NETWORK: mynetwork
DEST_RANGE: 10.168.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0

NAME: default-route-f93e5c4095524370
NETWORK: mynetwork
DEST_RANGE: 10.142.0.0/20
NEXT_HOP: mynetwork
PRIORITY: 0
----

[source, bash]
.*gcloud compute firewall-rules list*
----
NAME: mynetwork-allow-custom
NETWORK: mynetwork
DIRECTION: INGRESS
PRIORITY: 65534
ALLOW: all
DENY: 
DISABLED: False

NAME: mynetwork-allow-icmp
NETWORK: mynetwork
DIRECTION: INGRESS
PRIORITY: 65534
ALLOW: icmp
DENY: 
DISABLED: False

NAME: mynetwork-allow-rdp
NETWORK: mynetwork
DIRECTION: INGRESS
PRIORITY: 65534
ALLOW: tcp:3389
DENY: 
DISABLED: False

NAME: mynetwork-allow-ssh
NETWORK: mynetwork
DIRECTION: INGRESS
PRIORITY: 65534
ALLOW: tcp:22
DENY: 
DISABLED: False
----

[source, bash]
.*gcloud compute networks list*
----
NAME: mynetwork
SUBNET_MODE: AUTO
BGP_ROUTING_MODE: REGIONAL
IPV4_RANGE: 
GATEWAY_IPV4: 
----

[source, bash]
.*gcloud compute networks subnets list*
----
NAME: mynetwork
REGION: us-central1
NETWORK: mynetwork
RANGE: 10.128.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: europe-west1
NETWORK: mynetwork
RANGE: 10.132.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: us-west1
NETWORK: mynetwork
RANGE: 10.138.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 

NAME: mynetwork
REGION: asia-east1
NETWORK: mynetwork
RANGE: 10.140.0.0/20
STACK_TYPE: IPV4_ONLY
IPV6_ACCESS_TYPE: 
INTERNAL_IPV6_PREFIX: 
EXTERNAL_IPV6_PREFIX: 
----

[source, bash]
.*gcloud compute firewall-rules list*
----
NAME: managementnet-allow-icmp-ssh-rdp
NETWORK: managementnet
DIRECTION: INGRESS
PRIORITY: 1000
ALLOW: tcp:22,tcp:3389,icmp
DENY: 
DISABLED: False

NAME: mynetwork-allow-custom
NETWORK: mynetwork
DIRECTION: INGRESS
PRIORITY: 65534
ALLOW: all
DENY: 
DISABLED: False

NAME: mynetwork-allow-icmp
NETWORK: mynetwork
DIRECTION: INGRESS
PRIORITY: 65534
ALLOW: icmp
DENY: 
DISABLED: False

NAME: mynetwork-allow-rdp
NETWORK: mynetwork
DIRECTION: INGRESS
PRIORITY: 65534
ALLOW: tcp:3389
DENY: 
DISABLED: False

NAME: mynetwork-allow-ssh
NETWORK: mynetwork
DIRECTION: INGRESS
PRIORITY: 65534
ALLOW: tcp:22
DENY: 
DISABLED: False

NAME: privatenet-allow-icmp-ssh-rdp
NETWORK: privatenet
DIRECTION: INGRESS
PRIORITY: 1000
ALLOW: icmp,tcp:22,tcp:3389
DENY: 
DISABLED: False
----
