apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-014
  namespace: gw-014
spec:
  host: gw014.example.com
  upstreams:
  - name: foo
    service: foo-svc
    port: 80
    sessionCookie:
      enable: true
      name: srv_id
      path: /
      expires: 1h
      domain: .example.com
      httpOnly: false
      secure: true
  routes:
  - path: /foo
    action:
      pass: foo
