apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: f5-manage10
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: f5-manage10
data:
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config-a
  namespace: f5-manage10
data:
  resolver-addresses: "197.4.209.2"

