apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-301
  namespace: gw-301
spec:
  host: gw301.example.com
  policies:
  - name: rate-limit-source-addr
  upstreams:
  - name: foo
    service: foo-svc
    port: 80
  routes:
  - path: /
    action:
      pass: foo
