apiVersion: v1
kind: Namespace
metadata:
  name: gw-103
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-app
  name: grpc-app
  namespace: gw-103
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-app
  template:
    metadata:
      labels:
        app: grpc-app
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/$PROJECT/nginx/grpc-go-greeting:0.1
        name: backend
        ports:
        - containerPort: 8009
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-app-svc
  namespace: gw-103
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8009
  selector:
    app: grpc-app
  type: ClusterIP
