apiVersion: v1
kind: Namespace
metadata:
  name: gw-103
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-app
  name: grpc-app
  namespace: gw-103
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-app
  template:
    metadata:
      labels:
        app: grpc-app
    spec:
      containers:
      - image: cloudadc/grpc-go-greeting:1.1
        name: backend
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-app-svc
  namespace: gw-103
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: grpc-app
  type: ClusterIP
