apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-103
  namespace: gw-103
spec:
  host: gw103.example.com
  tls:
    secret: grpc-secret
  upstreams:
  - name: grpc-app
    service: grpc-app-svc
    port: 50051
    type: grpc
  routes:
  - path: /helloworld.Greeter
    action:
      pass: grpc-app
