apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-016
  namespace: gw-016
spec:
  host: gw016.example.com
  upstreams:
  - name: foo
    service: foo-svc
    port: 80
  routes:
  - path: /
    action:
      pass: foo
