apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: nginx-ingress
spec:
  ports:
  - port: 8898
    protocol: TCP
    targetPort: 8898
  selector:
    app: nginx-ingress
  type: LoadBalancer
