apiVersion: v1
kind: Namespace
metadata:
  name: test-21
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: test-21
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: test-21
data:
