apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-3-3-15
  namespace: f5-manage09
spec:
  host: ws.f5manage09.test.cmbc.com
  upstreams:
  - name: ws-app
    service: ws-app-svc
    port: 80
  routes:
  - path: /
    action:
      pass: ws-app
  - path: /rlzy/websocket
    action:
      pass: ws-app
