apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-010
  namespace: gw-010
spec:
  host: gw010.example.com
  upstreams:
  - name: foo-v1
    service: foo-v1-svc
    port: 80
  - name: foo-v2
    service: foo-v2-svc
    port: 80
  routes:
  - path: /variables
    action:
      return:
        code: 200
        type: text/plain
        body: "remote_addr: ${remote_addr}\nremote_port: ${remote_port}\nrequest_uri: ${request_uri}\nrequest_method: ${request_method}\n"
  - path: /
    matches:
    - conditions:
      - variable: $request_uri
        value: ~*v2$
      action:
        pass: foo-v2
    action:
      pass: foo-v1

