apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-402
  namespace: gw-402
spec:
  http-snippets: |
    limit_conn_zone $server_name zone=max_conn_zone:10m;
  host: gw402.example.com
  server-snippets: |
    limit_conn max_conn_zone 1000;
  upstreams:
  - name: foo
    service: foo-svc
    port: 80
  routes:
  - path: /
    action:
      pass: foo
