apiVersion: v1
data:
  httpd.conf: |
    listen 10010
    ###################
    Include /apache/httpd/conf/public.conf
    Include /apache/httpd/conf/servername.conf
    Include /apache/apache_apache_10010/uid.conf
    ###################Modules######################
    LoadModule status_module                /apache/httpd/modules/mod_status.so
    LoadModule rewrite_module               /apache/httpd/modules/mod_rewrite.so
    LoadModule proxy_module                 /apache/httpd/modules/mod_proxy.so
    LoadModule proxy_http_module            /apache/httpd/modules/mod_proxy_http.so
    #LoadModule ssl_module                  /apache/httpd/modules/mod_ssl.so
    #LoadModule weblogic_module             /apache/httpd/modules/mod_wl.so
    KeepAlive On
    MaxKeepAliveRequests 10000
    KeepAliveTimeout 15
    ListenBacklog 1000
    Pidfile "/apache/apache_apache_10010/apache.pid"
    LogFormat "%h %l %u %t \"%r\" %>s %b %{Foobar}C" common
    #CustomLog "|/apache/httpd/bin/rotatelogs -n 2 /apache/apache_apache_10010/logs/access/apache_access_log 1024M" combined
    #ErrorLog "/apache/apache_apache_10010/logs/error/error_log"
    CustomLog /dev/stdout combined
    ErrorLog /dev/stdout


    ProxyPreserveHost On
    ProxyPass "/"  "http://197.0.208.167:30657/"
    ProxyPassReverse "/"  "http://197.0.208.167:30657/"
    ServerName "session.f5manage02.test.cmbc.com"


    ExtendedStatus on
    <Location "/server-status">
    SetHandler server-status
    Require all granted
    </Location>
kind: ConfigMap
metadata:
  name: httpd-reverse-proxy-config
  namespace: f5-manage02
