apiVersion: v1
kind: Namespace
metadata:
  name: test-15
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: test-15
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: test-15
data:
  http-snippets: |
    upstream test-15-user.test15.example.com-31008 {
        zone test-15-user.test15.example.com-31008 512k;
        random two least_conn;
        server 10.128.0.3:31008 max_fails=1 fail_timeout=10s max_conns=0;
        server 10.128.0.4:31008 max_fails=1 fail_timeout=10s max_conns=0;
        sticky cookie nginx_user-svc_31008;
        queue 500 timeout=4s;
    }
    match user_server_ok {
        status 200-399;
        body ~ "health";
    }
    server {
        listen 80;
        listen [::]:80;
        server_tokens "off";
        server_name user.test15.example.com;
        status_zone user.test15.example.com;
        location / {
                proxy_http_version 1.1;
                proxy_connect_timeout 60s;
                proxy_read_timeout 60s;
                proxy_send_timeout 60s;
                client_max_body_size 1m;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering on;
                health_check interval=10 passes=2 fails=3 uri=/health match=user_server_ok;
                proxy_pass http://test-15-user.test15.example.com-31008;
        }
    }

    upstream test-15-order.test15.example.com-31009 {
        zone test-15-order.test15.example.com-31009 512k;
        random two least_conn;
        server 10.128.0.3:31009 max_fails=1 fail_timeout=10s max_conns=0;
        server 10.128.0.4:31009 max_fails=1 fail_timeout=10s max_conns=0;
        sticky cookie nginx_order-svc_31009;
        queue 500 timeout=4s;
    }
    match order_server_ok {
        status 200-399;
        body ~ "health";
    }
    server {
        listen 80;
        listen [::]:80;
        server_tokens "off";
        server_name order.test15.example.com;
        status_zone order.test15.example.com;
        location / {
                proxy_http_version 1.1;
                proxy_connect_timeout 60s;
                proxy_read_timeout 60s;
                proxy_send_timeout 60s;
                client_max_body_size 1m;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering on;
                health_check interval=10 passes=2 fails=3 uri=/health match=order_server_ok;
                proxy_pass http://test-15-order.test15.example.com-31009;
        }
    }
