apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-3-3-3
  namespace: f5-manage02
spec:
  host: gw.keepalive.f5manage02.test.cmbc.com
  ingressClassName: nginx-gw
  upstreams:
  - name: coffee-app
    service: coffee-svc
    port: 80
    keepalive: 30
  routes:
  - path: /coffee
    action:
      pass: coffee-app
