apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: observability
spec:
  selector:
    app: prometheus-server
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
