apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-006
  namespace: gw-006
spec:
  host: gw006.example.com
  upstreams:
  - name: foo
    service: foo-svc
    port: 80
    healthCheck:
      enable: true
      path: /health
      interval: 20s
      jitter: 3s
      fails: 5
      passes: 5
      port: 8080
      connect-timeout: 10s
      read-timeout: 10s
      send-timeout: 10s
      headers:
      - name: Host
        value: test.nginx.com
      statusMatch: "! 500"
  routes:
  - path: /foo
    action:
      pass: foo
