= Virtual Machines
:toc: manual

== Machines Types

The `gcloud compute machine-types list` can list all machine types in all regions, link:machine-types.json[machine-types.json] downloaded by `gcloud compute machine-types list --format=json` commands, and be loaded into mongodb, then use mongodb SQL to analysis this data.

[source, bash]
.*Create View*
----
var pipeline = [
  {
    $project: {
      _id: 0,
      name: 1,
      type: {$substr: ["$name", 0, {$indexOfCP: ["$name", "-"]}]},
      id: 1,
      imageSpaceGb: 1,
      guestCpus: 1,
      isSharedCpu: 1,
      memoryMb: 1,
      maximumPersistentDisks: 1,
      maximumPersistentDisksSizeGb: 1,
      zone: 1,
      guestAcceleratorCount: {$arrayElemAt: ["$accelerators.guestAcceleratorCount", 0]},
      guestAcceleratorType: {$arrayElemAt: ["$accelerators.guestAcceleratorType", 0]}
    }
  }
]

db.createView("machinetypes", "allmachinetypes", pipeline)
----

=== How many types?

[source, bash]
----
gcp> db.machinetypes.countDocuments()
12221
----

=== How many series?

[source, bash]
----
gcp> db.machinetypes.aggregate([{$group: {_id: "$type", count: {$count: {}}}}, {$sort: {count: -1}}])
[
  { _id: 'n2', count: 2962 },
  { _id: 'n2d', count: 2635 },
  { _id: 'n1', count: 2443 },
  { _id: 'e2', count: 1904 },
  { _id: 'c2d', count: 714 },
  { _id: 'c2', count: 400 },
  { _id: 't2d', count: 336 },
  { _id: 'm1', count: 263 },
  { _id: 'm2', count: 172 },
  { _id: 'f1', count: 98 },
  { _id: 'g1', count: 98 },
  { _id: 'a2', count: 88 },
  { _id: 't2a', count: 63 },
  { _id: 'm3', count: 45 }
]
----

Note that these 14 series belong to four types of machine families:

|===
|Machine families |Machine series

|General-purpose
|n2, n2d, n1, e2, t2d,t2a

|Compute-optimized
|c2d, c2

|Memory-optimized
|m1, m2, m3 

|Accelerator-optimized
|a2
|===

=== How many types per zone?

[source, bash]
----
gcp> db.machinetypes.aggregate([{$group: {_id: "$zone", count: {$count: {}}}}, {$sort: {count: -1}}])
[
  { _id: 'us-central1-b', count: 164 },
  { _id: 'europe-west4-b', count: 164 },
  { _id: 'us-central1-a', count: 164 },
  { _id: 'europe-west4-a', count: 162 },
  { _id: 'us-central1-c', count: 156 },
  { _id: 'europe-west4-c', count: 154 },
  { _id: 'asia-southeast1-b', count: 154 },
  { _id: 'asia-southeast1-c', count: 153 },
  { _id: 'europe-west3-b', count: 152 },
  { _id: 'europe-west3-a', count: 152 },
  { _id: 'us-central1-f', count: 147 },
  { _id: 'us-east4-c', count: 147 },
  { _id: 'us-east4-b', count: 147 },
  { _id: 'europe-west1-b', count: 147 },
  { _id: 'europe-west1-d', count: 147 },
  { _id: 'us-east1-b', count: 147 },
  { _id: 'us-west1-b', count: 147 },
  { _id: 'us-east4-a', count: 146 },
  { _id: 'us-east1-d', count: 143 },
  { _id: 'us-west1-a', count: 143 },
  { _id: 'asia-southeast1-a', count: 143 },
  { _id: 'asia-east1-b', count: 143 },
  { _id: 'europe-west3-c', count: 143 },
  { _id: 'us-central1-d', count: 142 },
  { _id: 'europe-west1-c', count: 139 },
  { _id: 'europe-west2-b', count: 138 },
  { _id: 'asia-south1-a', count: 138 },
  { _id: 'asia-south1-b', count: 138 },
  { _id: 'us-east1-c', count: 137 },
  { _id: 'us-west1-c', count: 135 },
  { _id: 'europe-west2-c', count: 134 },
  { _id: 'us-west4-b', count: 134 },
  { _id: 'asia-east1-a', count: 132 },
  { _id: 'asia-south1-c', count: 131 },
  { _id: 'us-west4-a', count: 130 },
  { _id: 'asia-northeast1-a', count: 129 },
  { _id: 'asia-east1-c', count: 128 },
  { _id: 'asia-northeast1-c', count: 125 },
  { _id: 'northamerica-northeast1-b', count: 124 },
  { _id: 'northamerica-northeast1-c', count: 124 },
  { _id: 'australia-southeast1-b', count: 122 },
  { _id: 'australia-southeast1-a', count: 122 },
  { _id: 'southamerica-east1-b', count: 119 },
  { _id: 'southamerica-east1-c', count: 119 },
  { _id: 'asia-northeast1-b', count: 119 },
  { _id: 'us-east1-a', count: 118 },
  { _id: 'australia-southeast1-c', count: 118 },
  { _id: 'europe-west2-a', count: 117 },
  { _id: 'asia-south2-a', count: 116 },
  { _id: 'asia-south2-b', count: 116 },
  { _id: 'asia-northeast3-a', count: 115 },
  { _id: 'us-west2-b', count: 112 },
  { _id: 'northamerica-northeast1-a', count: 112 },
  { _id: 'asia-northeast2-c', count: 111 },
  { _id: 'asia-northeast2-b', count: 111 },
  { _id: 'us-west3-b', count: 110 },
  { _id: 'southamerica-east1-a', count: 109 },
  { _id: 'asia-northeast2-a', count: 107 },
  { _id: 'europe-central2-b', count: 107 },
  { _id: 'us-west3-a', count: 106 },
  { _id: 'us-west2-a', count: 106 },
  { _id: 'us-west4-c', count: 106 },
  { _id: 'us-west3-c', count: 106 },
  { _id: 'asia-south2-c', count: 101 },
  { _id: 'asia-east2-a', count: 101 },
  { _id: 'europe-north1-a', count: 101 },
  { _id: 'asia-east2-b', count: 101 },
  { _id: 'asia-east2-c', count: 101 },
  { _id: 'europe-north1-c', count: 101 },
  { _id: 'europe-north1-b', count: 101 },
  { _id: 'me-west1-c', count: 100 },
  { _id: 'me-west1-b', count: 94 },
  { _id: 'asia-northeast3-b', count: 84 },
  { _id: 'europe-west8-c', count: 82 },
  { _id: 'us-east5-a', count: 82 },
  { _id: 'europe-west8-a', count: 82 },
  { _id: 'europe-west6-c', count: 80 },
  { _id: 'europe-west6-b', count: 80 },
  { _id: 'europe-southwest1-a', count: 78 },
  { _id: 'europe-west9-b', count: 78 },
  { _id: 'europe-southwest1-c', count: 78 },
  { _id: 'europe-west9-c', count: 78 },
  { _id: 'me-west1-a', count: 78 },
  { _id: 'us-west2-c', count: 77 },
  { _id: 'us-east5-c', count: 77 },
  { _id: 'us-east5-b', count: 77 },
  { _id: 'asia-northeast3-c', count: 75 },
  { _id: 'northamerica-northeast2-a', count: 74 },
  { _id: 'australia-southeast2-c', count: 74 },
  { _id: 'northamerica-northeast2-b', count: 74 },
  { _id: 'australia-southeast2-b', count: 74 },
  { _id: 'europe-central2-a', count: 74 },
  { _id: 'europe-west6-a', count: 73 },
  { _id: 'asia-southeast2-c', count: 73 },
  { _id: 'asia-southeast2-a', count: 73 },
  { _id: 'europe-west9-a', count: 72 },
  { _id: 'europe-west8-b', count: 72 },
  { _id: 'europe-southwest1-b', count: 72 },
  { _id: 'europe-central2-c', count: 68 },
  { _id: 'australia-southeast2-a', count: 68 },
  { _id: 'asia-southeast2-b', count: 65 },
  { _id: 'northamerica-northeast2-c', count: 65 },
  { _id: 'southamerica-west1-b', count: 56 },
  { _id: 'southamerica-west1-c', count: 56 },
  { _id: 'us-central2-a', count: 53 },
  { _id: 'us-central2-b', count: 53 },
  { _id: 'us-central2-c', count: 53 },
  { _id: 'southamerica-west1-a', count: 46 },
  { _id: 'us-east7-a', count: 45 },
  { _id: 'us-east7-b', count: 44 },
  { _id: 'us-east7-c', count: 44 },
  { _id: 'us-south1-a', count: 41 },
  { _id: 'us-south1-c', count: 41 },
  { _id: 'us-south1-b', count: 41 },
  { _id: 'europe-west5-b', count: 36 },
  { _id: 'europe-west5-c', count: 36 },
  { _id: 'us-east2-a', count: 35 },
  { _id: 'europe-west5-a', count: 32 },
  { _id: 'us-central2-d', count: 24 }
]
---- 

=== How many series in asia-northeast1-b?

[source, bash]
----
gcp> db.machinetypes.aggregate([{$match: {zone: {$eq: "asia-southeast1-b"}}}, {$group: {_id: "$type", count: {$count: {}}}}, {$sort: {count: -1}}])
[
  { _id: 'n2d', count: 31 },
  { _id: 'n2', count: 29 },
  { _id: 'n1', count: 26 },
  { _id: 'c2d', count: 21 },
  { _id: 'e2', count: 17 },
  { _id: 't2d', count: 8 },
  { _id: 't2a', count: 7 },
  { _id: 'c2', count: 5 },
  { _id: 'm1', count: 4 },
  { _id: 'a2', count: 4 },
  { _id: 'g1', count: 1 },
  { _id: 'f1', count: 1 }
]
----

=== What's hotest 30 categories by CPU and Memory?

[source, bash]
----
gcp> db.machinetypes.aggregate([{$group: {_id: {cpu: "$guestCpus", memory: "$memoryMb"}, count: {$count: {}}}}, {$sort: {count: -1}}])
[
  { _id: { cpu: 4, memory: 16384 }, count: 473 },
  { _id: { cpu: 8, memory: 32768 }, count: 473 },
  { _id: { cpu: 16, memory: 65536 }, count: 473 },
  { _id: { cpu: 2, memory: 2048 }, count: 420 },
  { _id: { cpu: 2, memory: 8192 }, count: 393 },
  { _id: { cpu: 32, memory: 131072 }, count: 393 },
  { _id: { cpu: 4, memory: 32768 }, count: 342 },
  { _id: { cpu: 8, memory: 65536 }, count: 342 },
  { _id: { cpu: 16, memory: 131072 }, count: 342 },
  { _id: { cpu: 2, memory: 16384 }, count: 342 },
  { _id: { cpu: 4, memory: 4096 }, count: 308 },
  { _id: { cpu: 8, memory: 8192 }, count: 308 },
  { _id: { cpu: 32, memory: 32768 }, count: 308 },
  { _id: { cpu: 16, memory: 16384 }, count: 308 },
  { _id: { cpu: 48, memory: 196608 }, count: 247 },
  { _id: { cpu: 32, memory: 262144 }, count: 230 },
  { _id: { cpu: 48, memory: 49152 }, count: 196 },
  { _id: { cpu: 64, memory: 65536 }, count: 196 },
  { _id: { cpu: 80, memory: 327680 }, count: 196 },
  { _id: { cpu: 64, memory: 262144 }, count: 196 },
  { _id: { cpu: 80, memory: 81920 }, count: 196 },
  { _id: { cpu: 48, memory: 393216 }, count: 196 },
  { _id: { cpu: 64, memory: 524288 }, count: 196 },
  { _id: { cpu: 80, memory: 655360 }, count: 196 },
  { _id: { cpu: 96, memory: 98304 }, count: 151 },
  { _id: { cpu: 128, memory: 524288 }, count: 151 },
  { _id: { cpu: 96, memory: 393216 }, count: 151 },
  { _id: { cpu: 40, memory: 984064 }, count: 146 },
  { _id: { cpu: 160, memory: 3936256 }, count: 146 },
  { _id: { cpu: 2, memory: 4096 }, count: 146 }
]
----

=== What's hotest 30 categories by CPU, Memory and Disk?

[source, bash]
----
gcp> db.machinetypes.aggregate([{$group: {_id: {cpu: "$guestCpus", memory: "$memoryMb", disk: "$maximumPersistentDisksSizeGb"}, count: {$count: {}}}}, {$sort: {count: -1}}, {$limit: 30}])
[
  { _id: { cpu: 4, memory: 16384, disk: '263168' }, count: 473 },
  { _id: { cpu: 16, memory: 65536, disk: '263168' }, count: 473 },
  { _id: { cpu: 8, memory: 32768, disk: '263168' }, count: 473 },
  { _id: { cpu: 32, memory: 131072, disk: '263168' }, count: 393 },
  { _id: { cpu: 2, memory: 8192, disk: '263168' }, count: 393 },
  { _id: { cpu: 4, memory: 32768, disk: '263168' }, count: 342 },
  { _id: { cpu: 8, memory: 65536, disk: '263168' }, count: 342 },
  { _id: { cpu: 2, memory: 16384, disk: '263168' }, count: 342 },
  { _id: { cpu: 16, memory: 131072, disk: '263168' }, count: 342 },
  { _id: { cpu: 2, memory: 2048, disk: '263168' }, count: 308 },
  { _id: { cpu: 8, memory: 8192, disk: '263168' }, count: 308 },
  { _id: { cpu: 32, memory: 32768, disk: '263168' }, count: 308 },
  { _id: { cpu: 4, memory: 4096, disk: '263168' }, count: 308 },
  { _id: { cpu: 16, memory: 16384, disk: '263168' }, count: 308 },
  { _id: { cpu: 48, memory: 196608, disk: '263168' }, count: 247 },
  { _id: { cpu: 32, memory: 262144, disk: '263168' }, count: 230 },
  { _id: { cpu: 80, memory: 655360, disk: '263168' }, count: 196 },
  { _id: { cpu: 80, memory: 327680, disk: '263168' }, count: 196 },
  { _id: { cpu: 64, memory: 524288, disk: '263168' }, count: 196 },
  { _id: { cpu: 64, memory: 262144, disk: '263168' }, count: 196 },
  { _id: { cpu: 48, memory: 393216, disk: '263168' }, count: 196 },
  { _id: { cpu: 64, memory: 65536, disk: '263168' }, count: 196 },
  { _id: { cpu: 80, memory: 81920, disk: '263168' }, count: 196 },
  { _id: { cpu: 48, memory: 49152, disk: '263168' }, count: 196 },
  { _id: { cpu: 128, memory: 524288, disk: '263168' }, count: 151 },
  { _id: { cpu: 96, memory: 393216, disk: '263168' }, count: 151 },
  { _id: { cpu: 96, memory: 98304, disk: '263168' }, count: 151 },
  { _id: { cpu: 2, memory: 4096, disk: '263168' }, count: 146 },
  { _id: { cpu: 160, memory: 3936256, disk: '263168' }, count: 146 },
  { _id: { cpu: 80, memory: 1968128, disk: '263168' }, count: 146 }
]
----

== Create VM

=== General-purpose Machine Series

From the GCP Console, there are six Series be used in Machine configuration.

.*Machine Series*
|===
|Series |Genrations |Notes

|N1
|FIRST GENERATION
|Powered by Intel Skylake platform or one of its predecessors

|E2
|SECOND GENERATION
|CPU Platform selection based on availability

|N2
|SECOND GENERATION
|Powered by Intel Cascade lake and Ice Lake CPU Platforms 

|N2D
|SECOND GENERATION
|Powered by AMD EPYC CPU Platform

|T2A
|SECOND GENERATION
|Powered by Ampere Altra ARM CPU Platform

|T2D
|SECOND GENERATION
|Powered by AMD EPYC Milan CPU Platform
|===

=== Create VM without External IP

[source, bash]
----
gcloud compute instances create test-instance-1 --zone=us-central1-c --machine-type=n1-standard-1 --network-interface=subnet=default,no-address --metadata=enable-oslogin=true --maintenance-policy=MIGRATE --provisioning-model=STANDARD --create-disk=auto-delete=yes,boot=yes,device-name=test-instance-1,image=projects/debian-cloud/global/images/debian-10-buster-v20221206,mode=rw,size=10,type=pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
----

* link:vm-test-instance-1.json[vm-test-instance-1.json]

=== Create Windows VM

[source, bash]
----
gcloud compute instances create test-instance-2 --zone=europe-west1-c --machine-type=n1-standard-2 --network-interface=network-tier=PREMIUM,subnet=default --metadata=enable-oslogin=true --maintenance-policy=MIGRATE --provisioning-model=STANDARD --tags=http-server,https-server --create-disk=auto-delete=yes,boot=yes,device-name=test-instance-2,image=projects/windows-cloud/global/images/windows-server-2016-dc-core-v20221214,mode=rw,size=100,type=pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
----

* link:vm-test-instance-2.json[vm-test-instance-2.json]

=== Create custom VM

[source, bash]
----
gcloud compute instances create test-instance-3 --zone=us-central1-a --machine-type=e2-custom-2-4096 --network-interface=network-tier=PREMIUM,subnet=default --metadata=enable-oslogin=true --maintenance-policy=MIGRATE --provisioning-model=STANDARD --create-disk=auto-delete=yes,boot=yes,device-name=test-instance-3,image=projects/debian-cloud/global/images/debian-10-buster-v20221206,mode=rw,size=10,type=pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
----

* link:vm-test-instance-3.json[vm-test-instance-3.json]

=== VM instances Comparision

The above 3 vms be import to MongoDB vm.vm collection, in this section use the Aggregations to compare 3 vms.

[source, bash]
.*Pipeline for cpuPlatform and machineType*
----
[
  {
    $match: {
      name: {$regex: "test-instance" }
    }
  },
  {
    $project: {
      _id: 0,
      cpuPlatform: 1,
      status: 1,
      name: 1,
      zone: {$substr: ["$zone", 82, -1]},
      machineType: {$substr: ["$machineType", {$add: [{$indexOfCP: ["$machineType", "machineType"]}, 13]}, -1]}
    }
  }
]
----

|===
|name |zone |status |cpuPlatform |machineType

|test-instance-1
|us-central1-c
|RUNNING
|Intel Haswell
|n1-standard-1

|test-instance-2
|europe-west1-c
|RUNNING
|Intel Haswell
|n1-standard-2

|test-instance-3
|us-central1-a
|RUNNING
|Intel Broadwell
|e2-custom-2-4096
|===


[source, bash]
.*Pipeline for Disks*
----
[
  {
    $match: {
      name: {$regex: "test-instance" }
    }
  },
  {
    $project: {
      _id: 0,
      disks: 1
    }
  },
  {
    $unwind: {
      path: "$disks"
    }
  },
  {
    $project: {
      deviceName: "$disks.deviceName",
      architecture: "$disks.architecture",
      size: "$disks.diskSizeGb",
      interface: "$disks.interface",
      kind: {$substr: ["$disks.kind", 8,-1]},
      mode: "$disks.mode",
      source: {$substr: ["$disks.source", {$add: [{$indexOfCP: ["$disks.source", "disks"]}, 6]}, -1]}
    }
  }
]
----

|===
|deviceName |architecture |size |interface |kind |mode |source

|test-instance-1
|X86_64
|10
|SCSI
|attachedDisk
|READ_WRITE
|test-instance-1

|test-instance-2
|X86_64
|100
|SCSI
|attachedDisk
|READ_WRITE
|test-instance-2

|test-instance-3
|X86_64
|10
|SCSI
|attachedDisk
|READ_WRITE
|test-instance-3
|===

[source, bash]
.*Pipeline for Networks*
----
[ 
  { 
    $match: {
      name: {$regex: "test-instance" }
    }
  },
  { 
    $project: {
      _id: 0,
      networkInterfaces: 1
    }
  },
  { 
    $unwind: {
      path: "$networkInterfaces"
    }
  },
  {
    $project: {
      name:"$networkInterfaces.name",
      network: {$substr: ["$networkInterfaces.network", 92, -1]},
      subnetwork: {$substr: ["$networkInterfaces.subnetwork", {$add: [{$indexOfCP: ["$networkInterfaces.subnetwork", "networks"]}, 9]}, -1]},
      networkIP: "$networkInterfaces.networkIP",
      accessname: {$arrayElemAt: ["$networkInterfaces.accessConfigs.name", 0]},
      natIP: {$arrayElemAt: ["$networkInterfaces.accessConfigs.natIP", 0]},
      natType: {$arrayElemAt: ["$networkInterfaces.accessConfigs.type", 0]}
    }
  }
]
----

|===
|name |network |subnetwork |networkIP |accessname |natIP |natType

|nic0
|default
|default
|10.128.0.2
|
|
|

|nic0
|default
|default
|10.128.0.3
|external-nat
|35.224.252.172
|ONE_TO_ONE_NAT

|nic0
|default
|default
|10.132.0.2
|external-nat
|34.76.22.158
|ONE_TO_ONE_NAT
|===
