= Virtual Machines
:toc: manual

== Machines Types

The `gcloud compute machine-types list` can list all machine types in all regions, link:machine-types.json[machine-types.json] downloaded by `gcloud compute machine-types list --format=json` commands, and be loaded into mongodb, then use mongodb SQL to analysis this data.

[source, bash]
.*Create View*
----
var pipeline = [
  {
    $project: {
      _id: 0,
      name: 1,
      type: {$substr: ["$name", 0, {$indexOfCP: ["$name", "-"]}]},
      id: 1,
      imageSpaceGb: 1,
      guestCpus: 1,
      isSharedCpu: 1,
      memoryMb: 1,
      maximumPersistentDisks: 1,
      maximumPersistentDisksSizeGb: 1,
      zone: 1,
      guestAcceleratorCount: {$arrayElemAt: ["$accelerators.guestAcceleratorCount", 0]},
      guestAcceleratorType: {$arrayElemAt: ["$accelerators.guestAcceleratorType", 0]}
    }
  }
]

db.createView("machinetypes", "allmachinetypes", pipeline)
----

=== How many types?

[source, bash]
----
gcp> db.machinetypes.countDocuments()
12221
----

=== How many series?

[source, bash]
----
gcp> db.machinetypes.aggregate([{$group: {_id: "$type", count: {$count: {}}}}, {$sort: {count: -1}}])
[
  { _id: 'n2', count: 2962 },
  { _id: 'n2d', count: 2635 },
  { _id: 'n1', count: 2443 },
  { _id: 'e2', count: 1904 },
  { _id: 'c2d', count: 714 },
  { _id: 'c2', count: 400 },
  { _id: 't2d', count: 336 },
  { _id: 'm1', count: 263 },
  { _id: 'm2', count: 172 },
  { _id: 'f1', count: 98 },
  { _id: 'g1', count: 98 },
  { _id: 'a2', count: 88 },
  { _id: 't2a', count: 63 },
  { _id: 'm3', count: 45 }
]
----

Note that these 14 series belong to four types of machine families:

|===
|Machine families |Machine series

|General-purpose
|n2, n2d, n1, e2, t2d,t2a

|Compute-optimized
|c2d, c2

|Memory-optimized
|m1, m2, m3 

|Accelerator-optimized
|a2
|===

=== How many types per zone?

[source, bash]
----
gcp> db.machinetypes.aggregate([{$group: {_id: "$zone", count: {$count: {}}}}, {$sort: {count: -1}}])
[
  { _id: 'us-central1-b', count: 164 },
  { _id: 'europe-west4-b', count: 164 },
  { _id: 'us-central1-a', count: 164 },
  { _id: 'europe-west4-a', count: 162 },
  { _id: 'us-central1-c', count: 156 },
  { _id: 'europe-west4-c', count: 154 },
  { _id: 'asia-southeast1-b', count: 154 },
  { _id: 'asia-southeast1-c', count: 153 },
  { _id: 'europe-west3-b', count: 152 },
  { _id: 'europe-west3-a', count: 152 },
  { _id: 'us-central1-f', count: 147 },
  { _id: 'us-east4-c', count: 147 },
  { _id: 'us-east4-b', count: 147 },
  { _id: 'europe-west1-b', count: 147 },
  { _id: 'europe-west1-d', count: 147 },
  { _id: 'us-east1-b', count: 147 },
  { _id: 'us-west1-b', count: 147 },
  { _id: 'us-east4-a', count: 146 },
  { _id: 'us-east1-d', count: 143 },
  { _id: 'us-west1-a', count: 143 },
  { _id: 'asia-southeast1-a', count: 143 },
  { _id: 'asia-east1-b', count: 143 },
  { _id: 'europe-west3-c', count: 143 },
  { _id: 'us-central1-d', count: 142 },
  { _id: 'europe-west1-c', count: 139 },
  { _id: 'europe-west2-b', count: 138 },
  { _id: 'asia-south1-a', count: 138 },
  { _id: 'asia-south1-b', count: 138 },
  { _id: 'us-east1-c', count: 137 },
  { _id: 'us-west1-c', count: 135 },
  { _id: 'europe-west2-c', count: 134 },
  { _id: 'us-west4-b', count: 134 },
  { _id: 'asia-east1-a', count: 132 },
  { _id: 'asia-south1-c', count: 131 },
  { _id: 'us-west4-a', count: 130 },
  { _id: 'asia-northeast1-a', count: 129 },
  { _id: 'asia-east1-c', count: 128 },
  { _id: 'asia-northeast1-c', count: 125 },
  { _id: 'northamerica-northeast1-b', count: 124 },
  { _id: 'northamerica-northeast1-c', count: 124 },
  { _id: 'australia-southeast1-b', count: 122 },
  { _id: 'australia-southeast1-a', count: 122 },
  { _id: 'southamerica-east1-b', count: 119 },
  { _id: 'southamerica-east1-c', count: 119 },
  { _id: 'asia-northeast1-b', count: 119 },
  { _id: 'us-east1-a', count: 118 },
  { _id: 'australia-southeast1-c', count: 118 },
  { _id: 'europe-west2-a', count: 117 },
  { _id: 'asia-south2-a', count: 116 },
  { _id: 'asia-south2-b', count: 116 },
  { _id: 'asia-northeast3-a', count: 115 },
  { _id: 'us-west2-b', count: 112 },
  { _id: 'northamerica-northeast1-a', count: 112 },
  { _id: 'asia-northeast2-c', count: 111 },
  { _id: 'asia-northeast2-b', count: 111 },
  { _id: 'us-west3-b', count: 110 },
  { _id: 'southamerica-east1-a', count: 109 },
  { _id: 'asia-northeast2-a', count: 107 },
  { _id: 'europe-central2-b', count: 107 },
  { _id: 'us-west3-a', count: 106 },
  { _id: 'us-west2-a', count: 106 },
  { _id: 'us-west4-c', count: 106 },
  { _id: 'us-west3-c', count: 106 },
  { _id: 'asia-south2-c', count: 101 },
  { _id: 'asia-east2-a', count: 101 },
  { _id: 'europe-north1-a', count: 101 },
  { _id: 'asia-east2-b', count: 101 },
  { _id: 'asia-east2-c', count: 101 },
  { _id: 'europe-north1-c', count: 101 },
  { _id: 'europe-north1-b', count: 101 },
  { _id: 'me-west1-c', count: 100 },
  { _id: 'me-west1-b', count: 94 },
  { _id: 'asia-northeast3-b', count: 84 },
  { _id: 'europe-west8-c', count: 82 },
  { _id: 'us-east5-a', count: 82 },
  { _id: 'europe-west8-a', count: 82 },
  { _id: 'europe-west6-c', count: 80 },
  { _id: 'europe-west6-b', count: 80 },
  { _id: 'europe-southwest1-a', count: 78 },
  { _id: 'europe-west9-b', count: 78 },
  { _id: 'europe-southwest1-c', count: 78 },
  { _id: 'europe-west9-c', count: 78 },
  { _id: 'me-west1-a', count: 78 },
  { _id: 'us-west2-c', count: 77 },
  { _id: 'us-east5-c', count: 77 },
  { _id: 'us-east5-b', count: 77 },
  { _id: 'asia-northeast3-c', count: 75 },
  { _id: 'northamerica-northeast2-a', count: 74 },
  { _id: 'australia-southeast2-c', count: 74 },
  { _id: 'northamerica-northeast2-b', count: 74 },
  { _id: 'australia-southeast2-b', count: 74 },
  { _id: 'europe-central2-a', count: 74 },
  { _id: 'europe-west6-a', count: 73 },
  { _id: 'asia-southeast2-c', count: 73 },
  { _id: 'asia-southeast2-a', count: 73 },
  { _id: 'europe-west9-a', count: 72 },
  { _id: 'europe-west8-b', count: 72 },
  { _id: 'europe-southwest1-b', count: 72 },
  { _id: 'europe-central2-c', count: 68 },
  { _id: 'australia-southeast2-a', count: 68 },
  { _id: 'asia-southeast2-b', count: 65 },
  { _id: 'northamerica-northeast2-c', count: 65 },
  { _id: 'southamerica-west1-b', count: 56 },
  { _id: 'southamerica-west1-c', count: 56 },
  { _id: 'us-central2-a', count: 53 },
  { _id: 'us-central2-b', count: 53 },
  { _id: 'us-central2-c', count: 53 },
  { _id: 'southamerica-west1-a', count: 46 },
  { _id: 'us-east7-a', count: 45 },
  { _id: 'us-east7-b', count: 44 },
  { _id: 'us-east7-c', count: 44 },
  { _id: 'us-south1-a', count: 41 },
  { _id: 'us-south1-c', count: 41 },
  { _id: 'us-south1-b', count: 41 },
  { _id: 'europe-west5-b', count: 36 },
  { _id: 'europe-west5-c', count: 36 },
  { _id: 'us-east2-a', count: 35 },
  { _id: 'europe-west5-a', count: 32 },
  { _id: 'us-central2-d', count: 24 }
]
---- 

=== How many series in asia-northeast1-b?

[source, bash]
----
gcp> db.machinetypes.aggregate([{$match: {zone: {$eq: "asia-southeast1-b"}}}, {$group: {_id: "$type", count: {$count: {}}}}, {$sort: {count: -1}}])
[
  { _id: 'n2d', count: 31 },
  { _id: 'n2', count: 29 },
  { _id: 'n1', count: 26 },
  { _id: 'c2d', count: 21 },
  { _id: 'e2', count: 17 },
  { _id: 't2d', count: 8 },
  { _id: 't2a', count: 7 },
  { _id: 'c2', count: 5 },
  { _id: 'm1', count: 4 },
  { _id: 'a2', count: 4 },
  { _id: 'g1', count: 1 },
  { _id: 'f1', count: 1 }
]
----

=== What's hotest 30 categories by CPU and Memory?

[source, bash]
----
gcp> db.machinetypes.aggregate([{$group: {_id: {cpu: "$guestCpus", memory: "$memoryMb"}, count: {$count: {}}}}, {$sort: {count: -1}}, {$limit: 30}])
[
  { _id: { cpu: 4, memory: 16384 }, count: 473 },
  { _id: { cpu: 8, memory: 32768 }, count: 473 },
  { _id: { cpu: 16, memory: 65536 }, count: 473 },
  { _id: { cpu: 2, memory: 2048 }, count: 420 },
  { _id: { cpu: 2, memory: 8192 }, count: 393 },
  { _id: { cpu: 32, memory: 131072 }, count: 393 },
  { _id: { cpu: 4, memory: 32768 }, count: 342 },
  { _id: { cpu: 8, memory: 65536 }, count: 342 },
  { _id: { cpu: 16, memory: 131072 }, count: 342 },
  { _id: { cpu: 2, memory: 16384 }, count: 342 },
  { _id: { cpu: 4, memory: 4096 }, count: 308 },
  { _id: { cpu: 8, memory: 8192 }, count: 308 },
  { _id: { cpu: 32, memory: 32768 }, count: 308 },
  { _id: { cpu: 16, memory: 16384 }, count: 308 },
  { _id: { cpu: 48, memory: 196608 }, count: 247 },
  { _id: { cpu: 32, memory: 262144 }, count: 230 },
  { _id: { cpu: 48, memory: 49152 }, count: 196 },
  { _id: { cpu: 64, memory: 65536 }, count: 196 },
  { _id: { cpu: 80, memory: 327680 }, count: 196 },
  { _id: { cpu: 64, memory: 262144 }, count: 196 },
  { _id: { cpu: 80, memory: 81920 }, count: 196 },
  { _id: { cpu: 48, memory: 393216 }, count: 196 },
  { _id: { cpu: 64, memory: 524288 }, count: 196 },
  { _id: { cpu: 80, memory: 655360 }, count: 196 },
  { _id: { cpu: 96, memory: 98304 }, count: 151 },
  { _id: { cpu: 128, memory: 524288 }, count: 151 },
  { _id: { cpu: 96, memory: 393216 }, count: 151 },
  { _id: { cpu: 40, memory: 984064 }, count: 146 },
  { _id: { cpu: 160, memory: 3936256 }, count: 146 },
  { _id: { cpu: 2, memory: 4096 }, count: 146 }
]
----

=== What's hotest 20 categories by CPU and Memory in asia-northeast1-b?

[source, bash]
----
gcp> db.machinetypes.aggregate([{$match: {zone: {$eq: "asia-southeast1-b"}}}, {$group: {_id: {cpu: "$guestCpus", memory: "$memoryMb"}, count: {$count: {}}}}, {$sort: {count: -1}}, {$limit: 20}])
[
  { _id: { cpu: 16, memory: 65536 }, count: 7 },
  { _id: { cpu: 8, memory: 32768 }, count: 7 },
  { _id: { cpu: 4, memory: 16384 }, count: 7 },
  { _id: { cpu: 2, memory: 8192 }, count: 6 },
  { _id: { cpu: 32, memory: 131072 }, count: 6 },
  { _id: { cpu: 8, memory: 65536 }, count: 4 },
  { _id: { cpu: 2, memory: 2048 }, count: 4 },
  { _id: { cpu: 2, memory: 16384 }, count: 4 },
  { _id: { cpu: 16, memory: 131072 }, count: 4 },
  { _id: { cpu: 4, memory: 32768 }, count: 4 },
  { _id: { cpu: 48, memory: 196608 }, count: 4 },
  { _id: { cpu: 32, memory: 262144 }, count: 3 },
  { _id: { cpu: 32, memory: 32768 }, count: 3 },
  { _id: { cpu: 8, memory: 8192 }, count: 3 },
  { _id: { cpu: 16, memory: 16384 }, count: 3 },
  { _id: { cpu: 4, memory: 4096 }, count: 3 },
  { _id: { cpu: 48, memory: 49152 }, count: 2 },
  { _id: { cpu: 80, memory: 327680 }, count: 2 },
  { _id: { cpu: 80, memory: 1968128 }, count: 2 },
  { _id: { cpu: 48, memory: 393216 }, count: 2 }
]
----

=== What's hotest 30 categories by CPU, Memory and Disk?

[source, bash]
----
gcp> db.machinetypes.aggregate([{$group: {_id: {cpu: "$guestCpus", memory: "$memoryMb", disk: "$maximumPersistentDisksSizeGb"}, count: {$count: {}}}}, {$sort: {count: -1}}, {$limit: 30}])
[
  { _id: { cpu: 4, memory: 16384, disk: '263168' }, count: 473 },
  { _id: { cpu: 16, memory: 65536, disk: '263168' }, count: 473 },
  { _id: { cpu: 8, memory: 32768, disk: '263168' }, count: 473 },
  { _id: { cpu: 32, memory: 131072, disk: '263168' }, count: 393 },
  { _id: { cpu: 2, memory: 8192, disk: '263168' }, count: 393 },
  { _id: { cpu: 4, memory: 32768, disk: '263168' }, count: 342 },
  { _id: { cpu: 8, memory: 65536, disk: '263168' }, count: 342 },
  { _id: { cpu: 2, memory: 16384, disk: '263168' }, count: 342 },
  { _id: { cpu: 16, memory: 131072, disk: '263168' }, count: 342 },
  { _id: { cpu: 2, memory: 2048, disk: '263168' }, count: 308 },
  { _id: { cpu: 8, memory: 8192, disk: '263168' }, count: 308 },
  { _id: { cpu: 32, memory: 32768, disk: '263168' }, count: 308 },
  { _id: { cpu: 4, memory: 4096, disk: '263168' }, count: 308 },
  { _id: { cpu: 16, memory: 16384, disk: '263168' }, count: 308 },
  { _id: { cpu: 48, memory: 196608, disk: '263168' }, count: 247 },
  { _id: { cpu: 32, memory: 262144, disk: '263168' }, count: 230 },
  { _id: { cpu: 80, memory: 655360, disk: '263168' }, count: 196 },
  { _id: { cpu: 80, memory: 327680, disk: '263168' }, count: 196 },
  { _id: { cpu: 64, memory: 524288, disk: '263168' }, count: 196 },
  { _id: { cpu: 64, memory: 262144, disk: '263168' }, count: 196 },
  { _id: { cpu: 48, memory: 393216, disk: '263168' }, count: 196 },
  { _id: { cpu: 64, memory: 65536, disk: '263168' }, count: 196 },
  { _id: { cpu: 80, memory: 81920, disk: '263168' }, count: 196 },
  { _id: { cpu: 48, memory: 49152, disk: '263168' }, count: 196 },
  { _id: { cpu: 128, memory: 524288, disk: '263168' }, count: 151 },
  { _id: { cpu: 96, memory: 393216, disk: '263168' }, count: 151 },
  { _id: { cpu: 96, memory: 98304, disk: '263168' }, count: 151 },
  { _id: { cpu: 2, memory: 4096, disk: '263168' }, count: 146 },
  { _id: { cpu: 160, memory: 3936256, disk: '263168' }, count: 146 },
  { _id: { cpu: 80, memory: 1968128, disk: '263168' }, count: 146 }
]
----

== Create VM

=== General-purpose Machine Series

From the GCP Console, there are six Series be used in Machine configuration.

.*Machine Series*
|===
|Series |Genrations |Notes

|N1
|FIRST GENERATION
|Powered by Intel Skylake platform or one of its predecessors

|E2
|SECOND GENERATION
|CPU Platform selection based on availability

|N2
|SECOND GENERATION
|Powered by Intel Cascade lake and Ice Lake CPU Platforms 

|N2D
|SECOND GENERATION
|Powered by AMD EPYC CPU Platform

|T2A
|SECOND GENERATION
|Powered by Ampere Altra ARM CPU Platform

|T2D
|SECOND GENERATION
|Powered by AMD EPYC Milan CPU Platform
|===

=== Create VM without External IP

[source, bash]
----
gcloud compute instances create test-instance-1 --zone=us-central1-c --machine-type=n1-standard-1 --network-interface=subnet=default,no-address --metadata=enable-oslogin=true --maintenance-policy=MIGRATE --provisioning-model=STANDARD --create-disk=auto-delete=yes,boot=yes,device-name=test-instance-1,image=projects/debian-cloud/global/images/debian-10-buster-v20221206,mode=rw,size=10,type=pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
----

* link:vm-test-instance-1.json[vm-test-instance-1.json]

=== Create Windows VM

[source, bash]
----
gcloud compute instances create test-instance-2 --zone=europe-west1-c --machine-type=n1-standard-2 --network-interface=network-tier=PREMIUM,subnet=default --metadata=enable-oslogin=true --maintenance-policy=MIGRATE --provisioning-model=STANDARD --tags=http-server,https-server --create-disk=auto-delete=yes,boot=yes,device-name=test-instance-2,image=projects/windows-cloud/global/images/windows-server-2016-dc-core-v20221214,mode=rw,size=100,type=pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
----

* link:vm-test-instance-2.json[vm-test-instance-2.json]

=== Create custom VM

[source, bash]
----
gcloud compute instances create test-instance-3 --zone=us-central1-a --machine-type=e2-custom-2-4096 --network-interface=network-tier=PREMIUM,subnet=default --metadata=enable-oslogin=true --maintenance-policy=MIGRATE --provisioning-model=STANDARD --create-disk=auto-delete=yes,boot=yes,device-name=test-instance-3,image=projects/debian-cloud/global/images/debian-10-buster-v20221206,mode=rw,size=10,type=pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
----

* link:vm-test-instance-3.json[vm-test-instance-3.json]

=== VM instances Comparision

The above 3 vms be import to MongoDB vm.vm collection, in this section use the Aggregations to compare 3 vms.

[source, bash]
.*Pipeline for cpuPlatform and machineType*
----
[
  {
    $match: {
      name: {$regex: "test-instance" }
    }
  },
  {
    $project: {
      _id: 0,
      cpuPlatform: 1,
      status: 1,
      name: 1,
      zone: {$substr: ["$zone", 82, -1]},
      machineType: {$substr: ["$machineType", {$add: [{$indexOfCP: ["$machineType", "machineType"]}, 13]}, -1]}
    }
  }
]
----

|===
|name |zone |status |cpuPlatform |machineType

|test-instance-1
|us-central1-c
|RUNNING
|Intel Haswell
|n1-standard-1

|test-instance-2
|europe-west1-c
|RUNNING
|Intel Haswell
|n1-standard-2

|test-instance-3
|us-central1-a
|RUNNING
|Intel Broadwell
|e2-custom-2-4096
|===


[source, bash]
.*Pipeline for Disks*
----
[
  {
    $match: {
      name: {$regex: "test-instance" }
    }
  },
  {
    $project: {
      _id: 0,
      disks: 1
    }
  },
  {
    $unwind: {
      path: "$disks"
    }
  },
  {
    $project: {
      deviceName: "$disks.deviceName",
      architecture: "$disks.architecture",
      size: "$disks.diskSizeGb",
      interface: "$disks.interface",
      kind: {$substr: ["$disks.kind", 8,-1]},
      mode: "$disks.mode",
      source: {$substr: ["$disks.source", {$add: [{$indexOfCP: ["$disks.source", "disks"]}, 6]}, -1]}
    }
  }
]
----

|===
|deviceName |architecture |size |interface |kind |mode |source

|test-instance-1
|X86_64
|10
|SCSI
|attachedDisk
|READ_WRITE
|test-instance-1

|test-instance-2
|X86_64
|100
|SCSI
|attachedDisk
|READ_WRITE
|test-instance-2

|test-instance-3
|X86_64
|10
|SCSI
|attachedDisk
|READ_WRITE
|test-instance-3
|===

[source, bash]
.*Pipeline for Networks*
----
[ 
  { 
    $match: {
      name: {$regex: "test-instance" }
    }
  },
  { 
    $project: {
      _id: 0,
      networkInterfaces: 1
    }
  },
  { 
    $unwind: {
      path: "$networkInterfaces"
    }
  },
  {
    $project: {
      name:"$networkInterfaces.name",
      network: {$substr: ["$networkInterfaces.network", 92, -1]},
      subnetwork: {$substr: ["$networkInterfaces.subnetwork", {$add: [{$indexOfCP: ["$networkInterfaces.subnetwork", "networks"]}, 9]}, -1]},
      networkIP: "$networkInterfaces.networkIP",
      accessname: {$arrayElemAt: ["$networkInterfaces.accessConfigs.name", 0]},
      natIP: {$arrayElemAt: ["$networkInterfaces.accessConfigs.natIP", 0]},
      natType: {$arrayElemAt: ["$networkInterfaces.accessConfigs.type", 0]}
    }
  }
]
----

|===
|name |network |subnetwork |networkIP |accessname |natIP |natType

|nic0
|default
|default
|10.128.0.2
|
|
|

|nic0
|default
|default
|10.128.0.3
|external-nat
|35.224.252.172
|ONE_TO_ONE_NAT

|nic0
|default
|default
|10.132.0.2
|external-nat
|34.76.22.158
|ONE_TO_ONE_NAT
|===

== Deploy App to VM

=== Create VM with static public IP and additional persist disk

[source, bash]
----
gcloud compute instances create mc-server --zone=us-central1-a --machine-type=e2-medium --network-interface=address=34.172.240.66,network-tier=PREMIUM,subnet=default --metadata=enable-oslogin=true --maintenance-policy=MIGRATE --provisioning-model=STANDARD --tags=minecraft-server --create-disk=auto-delete=yes,boot=yes,device-name=mc-server,image=projects/debian-cloud/global/images/debian-11-bullseye-v20221206,mode=rw,size=10,type=pd-balanced --create-disk=device-name=minecraft-disk,mode=rw,name=minecraft-disk,size=50,type=pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
----

* link:vm-mc-server.json[vm-mc-server.json]

=== SSH to VM, format disk to ext4 type file system and mount to VM 

[source, bash]
.*1. Review Block Device*
----
$ lsblk 
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    0   10G  0 disk 
├─sda1    8:1    0  9.9G  0 part /
├─sda14   8:14   0    3M  0 part 
└─sda15   8:15   0  124M  0 part /boot/efi
sdb       8:16   0   50G  0 disk
----

Note that there are 2 disks, one has partitions and mounted as file system, the other is idle.

[source, bash]
.*2. Further review sdb device by id*
----
$ ls -l /dev/sdb 
brw-rw---- 1 root disk 8, 16 Jan  4 14:35 /dev/sdb

$ sudo ls -l /dev/disk/by-id/google-minecraft-disk 
lrwxrwxrwx 1 root root 9 Jan  4 14:35 /dev/disk/by-id/google-minecraft-disk -> ../../sdb
----

[source, bash]
.*3. Format the disk with ext4 file system type, *
----
$ sudo mkfs.ext4 -F -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/disk/by-id/google-minecraft-disk
mke2fs 1.46.2 (28-Feb-2021)
Discarding device blocks: done                            
Creating filesystem with 13107200 4k blocks and 3276800 inodes
Filesystem UUID: 50bc3477-84f7-4859-b288-9f93919f905f
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
        4096000, 7962624, 11239424

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (65536 blocks): done
Writing superblocks and filesystem accounting information: done  
----

[source, bash]
.*4. Create mount point and mount disk*
----
$ sudo mkdir -p /home/minecraft
$ sudo mount -o discard,defaults /dev/disk/by-id/google-minecraft-disk /home/minecraft
----

[source, bash]
.*5. Review disk and mounted file system*
----
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           394M  356K  393M   1% /run
/dev/sda1       9.7G  1.7G  7.5G  19% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      124M  5.9M  118M   5% /boot/efi
/dev/sdb         49G   24K   47G   1% /home/minecraft
----

=== Create firewall rule to allow VM ingress traffic on specific port 

[source, bash]
----
gcloud compute firewall-rules create minecraft-rule --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=tcp:25565 --source-ranges=0.0.0.0/0 --target-tags=minecraft-server
----

=== Perform regular backup application data to Cloud Storage

[source, bash]
.*1. Create Bucket*
----
gsutil mb gs://$BUCKET_NAME-minecraft-backup
----

[source, bash]
.*2. Create application backup script*
----
#!/bin/bash
screen -r mcs -X stuff '/save-all\n/save-off\n'
/usr/bin/gsutil cp -R ${BASH_SOURCE%/*}/world gs://${BUCKET_NAME}-minecraft-backup/$(date "+%Y%m%d-%H%M%S")-world
screen -r mcs -X stuff '/save-on\n'
----

[source, bash]
.*3. Cron job for regular run backup.sh*
----
$ sudo crontab -e

// add the following line, this will schedule a cron job run per 4 hours
0 */4 * * * /home/minecraft/backup.sh
----

=== Add start/stop script for VM maintenance

[source, bash]
----
$ gcloud compute instances list --format=json
...
    "metadata": {
      "fingerprint": "ExB_fWFxnwU=",
      "items": [
        {
          "key": "startup-script-url",
          "value": "https://storage.googleapis.com/cloud-training/archinfra/mcserver/startup.sh"
        },
        {
          "key": "shutdown-script-url",
          "value": "https://storage.googleapis.com/cloud-training/archinfra/mcserver/shutdown.sh"
        }
      ],
...
----

== Create Preemptible VMs

[source, bash]
.*Create 3 preemptible VMs*
----
gcloud compute instances create t1 t2 t3 --zone=us-east1-b --machine-type=e2-micro --preemptible
----

[source, bash]
.*List all VMs*
----
gcloud compute instances list --format=json
----

link:preemptible-vms.json[preemptible-vms.json]

== Managed Instance Group

=== Create an Instance Template

[source, bash]
----
gcloud compute instance-templates create instance-template-1 --machine-type=e2-micro --network-interface=network=default,network-tier=PREMIUM --maintenance-policy=MIGRATE --provisioning-model=STANDARD --tags=http-server,https-server --create-disk=auto-delete=yes,boot=yes,device-name=instance-template-1,image=projects/debian-cloud/global/images/debian-11-bullseye-v20230206,mode=rw,size=10,type=pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
----

=== Create a Health Check

[source, bash]
----
gcloud beta compute health-checks create tcp acloud-hc --port=80 --proxy-header=NONE --no-enable-logging --check-interval=10 --timeout=5 --unhealthy-threshold=2 --healthy-threshold=2
----

=== Create a Managed Instance Group

[source, bash]
.*1. create instance group*
----
gcloud beta compute instance-groups managed create instance-group-1 --base-instance-name=instance-group-1 --size=1 --template=instance-template-1 --zone=us-central1-a --list-managed-instances-results=PAGELESS --health-check=acloud-hc --initial-delay=300 --no-force-update-on-repair
----

[source, bash]
.*2. set autoscaling*
----
gcloud beta compute instance-groups managed set-autoscaling instance-group-1 --zone=us-central1-a --cool-down-period=60 --max-num-replicas=3 --min-num-replicas=1 --mode=on --target-cpu-utilization=0.6
----

=== Stress Test

[source, bash]
----
sudo apt-get install stress -y
sudo stress --cpu 8 --timeout 20
----

=== Depiction configurations

* link:mig-instance-templates.yaml[mig-instance-templates.yaml]
* link:mig-health-checks.yaml[mig-health-checks.yaml]
* link:mig-instance-groups.yaml[mig-instance-groups.yaml]
* link:mig-instances.yaml[mig-instances.yaml]

== TODO

[source, bash]
.**
----

----
