apiVersion: k8s.nginx.org/v1
kind: TransportServer
metadata:
  name: tencent
  namespace: cmbc
spec:
  listener:
    name: tls-passthrough
    protocol: TLS_PASSTHROUGH
  host: www.tencent.com
  upstreams:
    - name: external-tencent
      service: external-service-tencent
      port: 443
  action:
    pass: external-tencent
