apiVersion: v1
kind: Namespace
metadata:
  name: f5-manage01
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: f5-manage01
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: f5-manage01
data: