apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: user-order-route
  namespace: gw-004-1
spec:
  host: gw004.example.com
  upstreams:
  - name: user
    service: user-svc
    port: 80
  - name: order
    service: order-svc
    port: 80
  subroutes:
  - path: /
    action:
      pass: user
  - path: /order
    action:
      pass: order
