apiVersion: v1
kind: Namespace
metadata:
  name: gw-004-3
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-004
  namespace: gw-004-3
spec:
  host: gw004.example.com
  routes:
  - path: /
    route: gw-004-1/user-order-route
  - path: /cart
    route: gw-004-2/cart-route
