apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-0054
  namespace: gw-0054
spec:
  http-snippets: |
    keyval_zone zone=abswitch:64k state=abswitch.keyval;
    keyval abswitch $abswitchvalue zone=abswitch;
  host: gw0054.example.com
  server-snippets: |
    add_header abswitch $abswitchvalue ;
  upstreams:
  - name: blue
    service: blue-svc
    port: 80
  - name: green
    service: green-svc
    port: 80
  routes:
  - path: /
    matches:
    - conditions:
      - header: abswitch
        value: "yes"
      action:
        pass: green
    action:
      pass: blue
