apiVersion: v1
kind: Namespace
metadata:
  name: test-12
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: test-12
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: test-12
data:
  resolver-addresses: "169.254.169.254"
