= 基于 NGINX 构建多云统一API网关平台
:toc: manual

== 开场

大家好，感谢你们今天出席 NGINX金融客户培训日活动，我是 F5 NGINX 的解决方案顾问，接下来的一个小时里，我与大家分享云现代应用趋势下，如何基于 NGINX 构建多云统一 API 网关平台。


首先，我简要介绍今天培训课程的整体安排，以及我们当前部分的内容。今天的培训内容分为三个部分：NGINX基础高级功能培训、NGINX API网关场景培训，以及NGINX云原生场景培训。刚刚，继奎老师已经完成了NGINX基础高级功能培训部分，NGINX 云原生场景培训会在下午进行。接下来我将为大家介绍NGINX API网关场景的相关内容。

本部分的主要内容是API网关三大场景：API路由、API限流、API接入控制，以及通过平台化的建设，实现NGINX规范化治理管理、保证业务运行的可靠性。

然而，接下来的培训不会依次介绍这些条目，而是会结合银行数据中心基础架构云化改造，和数据中心应用现代化微服务改造的转型进程。我们将介绍云化基础架构，和微服务化应用架构，对负载均衡和反向代理这一基础能力提出的新需求和挑战，然后说明本部分的主要内容，API路由、API限流、API接入控制、平台化的治理管理是如何解决这些需求和挑战的。

== 现代应用

什么是现代应用？

现代应用就是采用新技术和方法构建的应用程序，当前银行正在推进已有传统应用的现代化改造，现代应用的显著特征是：微服务架构、容器化和K8S、云原生、自动化能力和CICD、可观测数据洞察。

微服务架构是将应用按需求模块分开建设，每个模块独立的项目组负责，通常在云中一个租户中部署，每个模块中又可拆分为多个独立的微服务，每个服务都专注于执行特定的业务功能。这种架构提供了更大的灵活性和可伸缩性，使企业能够更快速地迭代、更快的部署、更快的创新。

一个业务需求如果通过传统架构开发是一个服务实现，而通过微服务架构开发，则可能由数百个服务实现，对数百个服务的管理治理则需要标准化和自动化，容器就是标准化应用，K8S则是自动化，自动化微服务应用生命周期的管理。容器和K8S已成为当前现代应用的运行平台，银行业在大力建设并支持关键业务。

云原生就是在云上运行现代应用，当前银行在大力推进全栈云的建设，为现代应用和业务诉求提供了弹性资源能力、自动化的基础架构设施、自动化和服务治理的理念和工具集，实现了更高的可靠性、可用性，提升了银行业务从业务需求描述到应用实现上线运行的效率。

现代应用通过快速上线、快速迭代为客户带来更好的数字化体验。

生成式AI最近两年最火热的话题，右下入解释了生成式 AI 的基本名词概念，生成式AI是深度学习的一个子集，深度学习是机器学习的一个子集、机器学习是人工智能的一个主要分支，深度学习是基于Neural Network Model, 是一种受人脑神经元工作方式启发而设计的计算模型，成年人大脑有50亿个神经云，通过接收外界的信息训练，具备自主判断等意识，生成式AI的大语言模型也是多级的神经元模型，通过海量数据，使得模型具备自主判断等意识，生成文本、图片、视频等。

深度学习模型已经存在很多年，这两年的火爆主要是生成式AI的应用成熟，基于生成式AI的应用进入普通人的日常工作和生活，生成式 AI 擅长情感分析类应用，可以在用户使用APP的过程中判断用户是否满意，提升用户的数字化体验，银行业在大力发展生成式 AI，典型的应用场景包括智能客服、文本代码生成等。

围绕生成式AI的应用是典型的现代应用，应用需要随需而变，当前生成式 AI 每个两周都会有巨大的新的创新、新的能力出现，为了让您的用户有更好的体验，您的应用必须具备快速迭代，随需而变的能力。

云和生成式AI都和阻力现代应用的发展，现代应用快速上线迭代需要代理或复杂也具备类似额能力，NGINX为现代应用而生，NGINX是目前最北广泛使用的反向代理、负载均衡，NGINX目前提供一系列产品，包括NGINX开源版，NGINX企业版，云容器NGINX版本，现代应用安全版本，NGINX集中管理，NGINX网关等产品，NGINX非常轻量级，社区版NGINX大小只有1.1MB,NGINX 企业版的容器镜像可以是17MB，NGINX非常受欢迎，Docker Hub 上 NGINX 容器镜像下载超过10亿，最多下载量一周超过7000万，针对中国银行客户信创建设，企业级订阅开源版本，提供在开源NGINX代码上开发增强模块的服务。

本部分介绍了现代应用，以及与现代应用相伴而生的NGINX，接下来我们简单说明一下云现代应用对负载均衡、反向代理提出的新需求，或银行业在面对应用现代改造，应用上云过程中可能遇到的挑战。

== 云现代应用趋势下负载均衡新挑战


