apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ttcp
  name: ttcp
  namespace: gw-105
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ttcp
  template:
    metadata:
      labels:
        app: ttcp
    spec:
      containers:
      - image: cloudadc/ttcp:1.14-2
        name: ttcp
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: ttcp-svc
  namespace: gw-105
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: ttcp
  sessionAffinity: None
  type: ClusterIP
