apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-008
  namespace: gw-008
spec:
  host: gw008.example.com
  upstreams:
  - name: foo
    service: foo-svc
    port: 80
  routes:
  - path: /foo
    action:
      proxy:
        upstream: foo
        rewritePath: /bar
