apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: f5-manage06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - image: cloudadc/cafe:1.5
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: f5-manage06
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: user
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: f5-manage06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - image: cloudadc/cafe:1.5
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: f5-manage06
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: order
  type: ClusterIP
