apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: nginx-ingress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-ingress
  type: LoadBalancer
