apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-tm-weight
  namespace: f5-manage07
spec:
  host: tm.weight.f5manage07.example.com
  upstreams:
  - name: user-v1
    service: user-v1-svc
    port: 80
  - name: user-v2
    service: user-v2-svc
    port: 80
  routes:
  - path: /user
    splits:
    - weight: 10
      action:
        pass: user-v2
    - weight: 90
      action:
        pass: user-v1

