apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: f5-manage10
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: f5-manage10
data:
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config-a
  namespace: f5-manage10
data:
  resolver-addresses: "197.4.209.2"
  http-snippets: |
    upstream f5-manage10-cart.f5manage10.test.cmbc.com-32308 {
        zone f5-manage10-cart.f5manage10.test.cmbc.com-32308 512k;
        random two least_conn;
        server 197.20.31.1:32308 max_fails=1 fail_timeout=10s max_conns=0;
        server 197.20.31.2:32308 max_fails=1 fail_timeout=10s max_conns=0;
        server 197.20.31.3:32308 max_fails=1 fail_timeout=10s max_conns=0;
        server 197.20.31.4:32308 max_fails=1 fail_timeout=10s max_conns=0;
        server 197.20.31.5:32308 max_fails=1 fail_timeout=10s max_conns=0;
        server 197.20.31.6:32308 max_fails=1 fail_timeout=10s max_conns=0;
        sticky cookie nginx_cart-svc_32308;
        queue 500 timeout=10s;
    }
    match cart_server_ok {
        status 200-399;
        body ~ "health";
    }
    server {
        listen 80;
        listen [::]:80;
        server_tokens "off";
        server_name f5manage10.test.cmbc.com;
        status_zone f5manage10.test.cmbc.com;
        location /cart {
                proxy_http_version 1.1;
                proxy_connect_timeout 60s;
                proxy_read_timeout 60s;
                proxy_send_timeout 60s;
                client_max_body_size 1m;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering on;
                health_check interval=10 passes=2 fails=3 uri=/health match=cart_server_ok;
                proxy_pass http://f5-manage10-cart.f5manage10.test.cmbc.com-32308;
        }
    }

