apiVersion: v1
kind: Namespace
metadata:
  name: gw-401
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foo
  name: foo
  namespace: gw-401
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - image: cloudadc/cafe:1.1
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: foo-svc
  namespace: gw-401
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: foo
  type: ClusterIP
