kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: f5-manage01
data:
  error-log-level: "warn"
  log-format: '[access]: $remote_addr - $remote_user [$time_local] "$request" $status $grpc_status $body_bytes_sent "$http_referer"  "$http_user_agent" "$http_x_forwarded_for" "$resource_name" "$resource_type" "$resource_namespace" "$service"'