apiVersion: v1
kind: Namespace
metadata:
  name: test-07
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: test-07
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: test-07
data:
  error-log-level: "warn"
  log-format:  '[access]: $remote_addr - $remote_user [$time_local] "$request" $status $grpc_status $body_bytes_sent "$http_referer"  "$http_user_agent" "$http_x_forwarded_for" "$resource_name" "$resource_type" "$resource_namespace" "$service"'
  http-snippets: |
    keyval_zone zone=tableKV:64k;
        keyval abswitch $abswitchvalue zone=tableKV;
        keyval $uri $enablelimit zone=tableKV;
        keyval key1 $value1 zone=tableKV;
        keyval key2 $value2 zone=tableKV;
        keyval key3 $value3 zone=tableKV;

        map $enablelimit $limit_key {
            default "";
            1  $binary_remote_addr;
            2  "jwt_token_jwt_claim";
        }

        limit_req_zone $limit_key zone=standard_zone:1m rate=1r/s;
        limit_req_zone $limit_key zone=premium_zone:1m rate=1000r/s; 