apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-302
  namespace: gw-302
spec:
  host: gw302.example.com
  policies:
  - name: rate-limit-uri
  upstreams:
  - name: foo
    service: foo-svc
    port: 80
  routes:
  - path: /
    action:
      pass: foo
