apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-501
  namespace: gw-501
spec:
  host: gw501.example.com
  upstreams:
  - name: user
    service: user-svc
    port: 80
    sessionCookie:
      enable: true
      name: srv_id
      path: /
      expires: 1h
      domain: .example.com
      httpOnly: false
      secure: true
  routes:
  - path: /
    action:
      pass: user
