apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-001
  namespace: gw-001
spec:
  host: gw001.example.com
  upstreams:
  - name: foo
    service: foo-svc
    port: 80
  - name: bar
    service: bar-svc
    port: 80
  routes:
  - path: /foo
    action:
      pass: foo
  - path: /bar
    action:
      pass: bar
