apiVersion: v1
kind: Namespace
metadata:
  name: test-17
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: test-17
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: test-17
data:
